### ISSUE TITLE
New ODE package

### ISSUE THREAD

**Issue by muralidn** [muralidn/Drasil#17]
Good Morning Dr. @smiths ,

A working prototype of Drasil with a new ODE library package that solves a Second Order ODE can be found here,

https://github.com/muralidn/Drasil/tree/PDSecondOrder/

I gave up trying to modify the existing `scipyODEPckg `and ended up writing a new package called `scipyODELSodaPkg`. This package calls the `odeint `method of Scipy, which solves an ODE (including second-order) using the LSODA solver.

Accordingly, I have modified my PD controller project; and upgraded the power plant to a second-order system. I did a preliminary verification of the SRS, Code and Output, and they look good. These are committed to the same tree.

Can you or someone else from the Drasil team please review the changes and let me know what you think? I am open to making any changes during the winter break as well to make this "pull ready". 

Thank You!
Naveen

**Comment by muralidn** [comment]
@smiths

Forgot to mention the commit ID :).

The ODE updates are with the commit ID: a4ed0e1bb

PD Controller project is added with the commit IDL 7674c9663

**Comment by smiths** [comment]
@muralidn, looks great.  I was easily able to pull your repo, run make and run your python code.  (The only change I had to make was to call python3, since that is how I'm set up on my local machine.)  I had a quick look through your SRS, and I don't see where the second order ODE enters.  Your IM looks like a first order ODE to me.  Am I missing something?

**Comment by muralidn** [comment]
Thank You Dr. @smiths.  The updated SRS is committed to the same branch as the Drasil updates. Here is the link to the new SRS, 

https://github.com/muralidn/Drasil/tree/PDSecondOrder/code/stable/pdController

Are you referring to the CAS-741 class repo?.

**Comment by muralidn** [comment]
Here is a screenshot of the new IM,

![image](https://user-images.githubusercontent.com/71282513/102807121-1c387a80-43e4-11eb-8ae4-95ee473cab3a.png)


I think Drasil cannot render the squared differential just yet.

**Comment by smiths** [comment]
@muralidn, yes, you are correct that Drasil doesn't yet represent second derivatives with the proper notation.  

I didn't see the changes because I was looking in the master branch.  I can see everything now and it looks good.  As a next step I'll point Dr. Carette toward your work.  

Is there a reason you haven't merged your changes into master?

**Comment by muralidn** [comment]
Thank You Dr. @smiths. I just wanted to quickly get your opinion on this implementation; I was not sure if creating an entirely new package was ok. 

I was thinking of creating a pull request directly from the branch after this. I guess I'll work on it now?

**Comment by smiths** [comment]
@muralidn, it is fine to leave your branch as it is.  I'll write Dr. Carette to see his preference for reviewing your work.

**Comment by muralidn** [comment]
Good afternoon Dr. @smiths ,

The code updates to Drasil has been merged with the pull request #2288.  I just created a new pull request #2289 that contains the PD Controller example. 

Please review and let me know if any changes are required for the SRS.

**Comment by smiths** [comment]
Good work @muralidn.  I don't know if Dr. Carette has processed the PR for the PD controller yet.  He and I will likely discuss whether we want to add it or not.  Your example is a good one, and it is nice to show how the new ODE solver code is used, but if we pull in a new example, we are obligating ourselves to maintain it going forward.  It isn't a reflection on  your example if we don't add it, just the reality that we don't want to have so many examples in Drasil that the code base is difficult to keep current.  There are still some significant changes in Drasil in the future, and having to update all of the example is time consuming.

**Comment by muralidn** [comment]
That makes sense Dr. @smiths. I was also thinking along the same lines since the new ODE package is most likely to be used in the DblPendulum example.

Hence I have closed the pull request, JacquesCarette#2289, but left the example's branch intact for future references.

Thanks again for the opportunity to use, and work-on Drasil :smiley:. I learned quite a lot during the whole effort!

**Comment by smiths** [comment]
Thank you @muralidn.  Thanks to you, and others, the experiment with using Drasil in 741 was a success.  I'll definitely be doing that again in the future.  :smile:
