### ISSUE TITLE
Drasil questions - rate of change of a signal

### ISSUE THREAD

**Issue by muralidn** [muralidn/Drasil#2]
@oluowoj @smiths

I need to find the rate of change of a signal, i.e. dx/dt. I am wondering if Drasil's ODE solver supports that. Please share your thoughts on this.

**Comment by smiths** [comment]
@muralidn, Drasil solves ODEs (look at the nopcm example: https://github.com/JacquesCarette/Drasil/tree/master/code/drasil-example/Drasil/NoPCM).  The ODE has to be in the standard form dy/dt = f(y, t).  Can you put your PD in this form?  I included a link in my review of your SRS that pointed in this direction.

**Comment by muralidn** [comment]
Thank You Dr. @smiths. The Integral controller is now removed from the scope, and the simulation now is just a PD controller. I am able to reduce this into an ODE. 

Quick follow-up question, I reviewed the NoPCM example, and a first-order ODE is used there.  To better demonstrate a PD controller I'd like to change my power plant into a second-order system (mass-spring-damper). So I wanted to double-check if Drasil can solve a second order ODE ?.

**Comment by smiths** [comment]
@muralidn, unfortunately Drasil currently only solves first order ODEs.  My understanding from discussion with Dr. Carette is that adding support for second order ODEs is close, but it isn't currently in Drasil.  It has been a while since I mentioned it, but if you were to add second order ODE support to Drasil, there are bonus marks available for 741.  :smile:

**Comment by muralidn** [comment]
Thank you Dr. @smiths. I looked at Drasil's source code, and at least from a python  (scipy) standpoint, 2nd order ODEs definitely seem achievable in the available timeframe.  I will experiment a little on it and let you know.

**Comment by smiths** [comment]
Sounds great!  If you have questions, we can ask Dr. Carette, or possibly Brooks, the original author of much of the ODE related code in Drasil.

**Comment by muralidn** [comment]
Closed with issue #17.
