### ISSUE TITLE
Drasil questions - Imperative programming constructs

### ISSUE THREAD

**Issue by muralidn** [muralidn/Drasil#3]
@oluowoj @smiths

Any hints on how to generate the following imperative features in Drasil?

- A loop
- Store a value in a variable (in a function scope).

Please let me know.

**Comment by smiths** [comment]
Drasil is written in a functional form.  It may generate imperative code with loops, but you don't write loops in Drasil.  I think you are going in the wrong direction if this seems to be necessary.

**Comment by muralidn** [comment]
Thanks for the response Dr. @smiths.

This is no longer an issue as the IM is resolved into an ODE (see #2).

**Comment by smiths** [comment]
Great.
