### ISSUE TITLE
Integration symbol in theoretical models

### ISSUE THREAD

**Issue by muralidn** [muralidn/Drasil#4]
@oluowoj @smiths

Laplace transform (see below) is a theoretical model in my project. Searched Drasil's Math API and I don't think there is a symbol for integration yet. Perhaps I was looking in the wrong location? If not, any pointers on how to proceed, attach a figure perhaps ?

![image](https://user-images.githubusercontent.com/71282513/99725924-d4b88900-2adb-11eb-96f9-e3509abe4bb8.png)

**Comment by muralidn** [comment]
@oluowoj pointed me to the relevant constructor. This issue is resolved.

**Comment by smiths** [comment]
Great!
