### ISSUE TITLE
Drasil SRS review

### ISSUE THREAD

**Issue by muralidn** [muralidn/Drasil#5]
@smiths 

The first draft of SRS generated with Drasil is ready for review here,

https://github.com/muralidn/Drasil/tree/PIDController/code/stable/pidController

I will be fixing "known" issues over the next couple of days.

**Comment by muralidn** [comment]
Closing this issue. Will create an issue in "main" branch.

**Comment by smiths** [comment]
@muralidn, it would have been fine to create the issues here, although I can see why you wanted to keep everything in the same place.  Including a report from your main repo back to the relevant Drasil source could would be useful.
